import fs from "node:fs";
import path from "node:path";

// client/ and server/ deploy as SEPARATE repositories (Hostinger builds
// client/ from a standalone repo that never contains server/), so
// client/src/lib/markupEngine.ts cannot be a cross-repo import — it's a
// physical copy of this file's code, regenerated by this script.
//
// Usage (run from server/):
//   npm run sync:markup-engine   — regenerates the client copy
//   npm run guard:markup-sync    — fails (exit 1) if the client copy is stale,
//                                  without writing anything (CI-safe)
//
// Both modes share this one generator so the sync and the check can never
// drift from each other's idea of what "in sync" means.

const SOURCE = path.join(__dirname, "..", "src", "lib", "markupEngine.ts");
const TARGET = path.join(__dirname, "..", "..", "client", "src", "lib", "markupEngine.ts");

const CLIENT_HEADER = `// Pricing module — synced copy of server/src/lib/markupEngine.ts.
//
// client/ and server/ deploy as SEPARATE repositories (Hostinger builds this
// app from a standalone "spaksTripClient" repo that does not contain server/
// at all) — a cross-repo relative import (../../../server/src/lib/...) only
// ever worked in the monorepo dev checkout and broke production builds. This
// file is a physical duplicate, not an import, so client/ is self-contained.
//
// SOURCE OF TRUTH IS server/src/lib/markupEngine.ts. Never hand-edit this
// file directly: edit the server copy, then run \`npm run sync:markup-engine\`
// (from server/) to regenerate this one, and commit both in the same change.
// \`npm run guard:markup-sync\` (server/) fails CI if the two ever drift apart.
//`;

const BODY_MARKER = "export type MarkupType";

function generateClientContent(): string {
  const source = fs.readFileSync(SOURCE, "utf8");
  const idx = source.indexOf(BODY_MARKER);
  if (idx === -1) {
    throw new Error(`Could not find "${BODY_MARKER}" in ${SOURCE} — has the file structure changed?`);
  }
  const body = source.slice(idx);
  return `${CLIENT_HEADER}\n\n${body}`;
}

function main(): void {
  const check = process.argv.includes("--check");
  const generated = generateClientContent();

  if (!check) {
    fs.writeFileSync(TARGET, generated);
    console.log(`✓ Synced ${TARGET}`);
    return;
  }

  const current = fs.existsSync(TARGET) ? fs.readFileSync(TARGET, "utf8") : null;
  if (current === generated) {
    console.log("✓ guard:markup-sync — client copy is in sync with server/src/lib/markupEngine.ts");
    process.exit(0);
  }

  console.error(
    "✗ guard:markup-sync — client/src/lib/markupEngine.ts is OUT OF SYNC with " +
      "server/src/lib/markupEngine.ts.\n\n" +
      "Run `npm run sync:markup-engine` (from server/), review the diff, and commit both files.",
  );
  process.exit(1);
}

main();
